# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/serval/daniel_shih/cnn_circuit/vivado_pro/IP/cnn_zynq/cnn.cache/wt [current_project]
set_property parent.project_path /home/serval/daniel_shih/cnn_circuit/vivado_pro/IP/cnn_zynq/cnn.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part e-elements:ego-xz7:part0:1.1 [current_project]
set_property ip_output_repo /home/serval/daniel_shih/cnn_circuit/vivado_pro/IP/cnn_zynq/cnn.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/serval/daniel_shih/cnn_circuit/cnn/src/param.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/cnn_ctrl.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/cnn_mem_sel.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/cnn_pset.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/conv.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/conv_addr.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/conv_ctrl.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/conv_loop.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/conv_unit.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/eras.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/maxp.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/maxp_addr.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/maxp_ctrl.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/maxp_loop.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/maxp_unit.v
  /home/serval/daniel_shih/cnn_circuit/cnn/src/cnn_zynq.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top cnn -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cnn.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cnn_utilization_synth.rpt -pb cnn_utilization_synth.pb"
