# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/icecr/appdata/roaming/xilinx/vivado/lenet/lenet.tmp/cnn_v1_0_project/cnn_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/icecr/appdata/roaming/xilinx/vivado/lenet/lenet.tmp/cnn_v1_0_project/cnn_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/users/icecr/appdata/roaming/xilinx/vivado/lenet/lenet.tmp/cnn_v1_0_project/cnn_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library "" {
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/param.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/cnn_ctrl.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/cnn_mem_sel.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/cnn_pset.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/conv.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/conv_addr.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/conv_ctrl.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/conv_loop.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/conv_unit.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/eras.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/maxp.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/maxp_addr.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/maxp_ctrl.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/maxp_loop.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/maxp_unit.v
  c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/sources_1/imports/src_zynq/cnn_zynq.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/constrs_1/imports/hw2/pynq-z2_v1.0.xdc
set_property used_in_implementation false [get_files c:/Users/icecr/AppData/Roaming/Xilinx/Vivado/layer-group-ip/layer-group-ip.srcs/constrs_1/imports/hw2/pynq-z2_v1.0.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cnn -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cnn.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cnn_utilization_synth.rpt -pb cnn_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
