# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths /home/serval/daniel_shih/cnn_circuit/vivado_pro/IP [current_project]
set_property ip_output_repo /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_2/design_1_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_1/design_1_blk_mem_gen_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_2/design_1_blk_mem_gen_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_3/design_1_axi_bram_ctrl_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_4/design_1_axi_bram_ctrl_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_10/bd_6e42_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_16/bd_6e42_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_23/bd_6e42_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_30/bd_6e42_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_37/bd_6e42_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_44/bd_6e42_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_51/bd_6e42_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_52/bd_6e42_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_53/bd_6e42_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_54/bd_6e42_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_55/bd_6e42_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_56/bd_6e42_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_45/bd_6e42_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_46/bd_6e42_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_47/bd_6e42_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_48/bd_6e42_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_49/bd_6e42_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_38/bd_6e42_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_39/bd_6e42_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_40/bd_6e42_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_41/bd_6e42_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_42/bd_6e42_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_31/bd_6e42_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_32/bd_6e42_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_33/bd_6e42_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_34/bd_6e42_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_35/bd_6e42_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_24/bd_6e42_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_25/bd_6e42_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_26/bd_6e42_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_27/bd_6e42_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_28/bd_6e42_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_17/bd_6e42_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_18/bd_6e42_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_19/bd_6e42_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_20/bd_6e42_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_21/bd_6e42_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_11/bd_6e42_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_12/bd_6e42_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_13/bd_6e42_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_14/bd_6e42_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_15/bd_6e42_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_2/bd_6e42_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_3/bd_6e42_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_4/bd_6e42_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/bd_6e42_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/bd_6e42_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_2/design_1_rst_ps7_0_50M_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_2/design_1_rst_ps7_0_50M_2.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_2/design_1_rst_ps7_0_50M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
