#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jun 26 15:55:24 CST 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 processing_system7_vip_v1_0_5 blk_mem_gen_v8_4_1 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 fifo_generator_v13_2_2 lib_fifo_v1_0_11 lib_cdc_v1_0_2 axi_datamover_v5_1_19 axi_sg_v4_1_10 axi_cdma_v4_1_17 blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_14 xlconstant_v1_1_5 proc_sys_reset_v5_0_12 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_19 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_17 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 axi_protocol_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/cnn_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/cnn_mem_sel.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/cnn_pset.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/conv.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/conv_addr.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/conv_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/conv_loop.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/conv_unit.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/eras.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/maxp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/maxp_addr.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/maxp_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/maxp_loop.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/maxp_unit.v" \
    "$ref_dir/../../../bd/design_1/ipshared/0c68/src/cnn_zynq.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_cnn_0_0/sim/design_1_cnn_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_0_1/sim/design_1_blk_mem_gen_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_0_2/sim/design_1_blk_mem_gen_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_1_0/sim/design_1_blk_mem_gen_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_1_1/sim/design_1_blk_mem_gen_1_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_1_2/sim/design_1_blk_mem_gen_1_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec8a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/6e5f/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_cdma_v4_1_17 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/1403/hdl/axi_cdma_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_cdma_0_0/sim/design_1_axi_cdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_14 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/6db1/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_1/sim/design_1_axi_bram_ctrl_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_2/sim/design_1_axi_bram_ctrl_0_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_3/sim/design_1_axi_bram_ctrl_0_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_4/sim/design_1_axi_bram_ctrl_0_4.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/sim/bd_6e42.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_10/sim/bd_6e42_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_16/sim/bd_6e42_m01s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_23/sim/bd_6e42_m02s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_30/sim/bd_6e42_m03s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_37/sim/bd_6e42_m04s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_44/sim/bd_6e42_m05s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_51/sim/bd_6e42_m06s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_57/sim/bd_6e42_m06e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_52/sim/bd_6e42_m06arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_53/sim/bd_6e42_m06rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_54/sim/bd_6e42_m06awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_55/sim/bd_6e42_m06wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_56/sim/bd_6e42_m06bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_50/sim/bd_6e42_m05e_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_45/sim/bd_6e42_m05arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_46/sim/bd_6e42_m05rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_47/sim/bd_6e42_m05awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_48/sim/bd_6e42_m05wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_49/sim/bd_6e42_m05bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_43/sim/bd_6e42_m04e_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_38/sim/bd_6e42_m04arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_39/sim/bd_6e42_m04rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_40/sim/bd_6e42_m04awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_41/sim/bd_6e42_m04wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_42/sim/bd_6e42_m04bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_36/sim/bd_6e42_m03e_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_31/sim/bd_6e42_m03arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_32/sim/bd_6e42_m03rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_33/sim/bd_6e42_m03awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_34/sim/bd_6e42_m03wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_35/sim/bd_6e42_m03bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_29/sim/bd_6e42_m02e_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_24/sim/bd_6e42_m02arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_25/sim/bd_6e42_m02rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_26/sim/bd_6e42_m02awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_27/sim/bd_6e42_m02wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_28/sim/bd_6e42_m02bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_22/sim/bd_6e42_m01e_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_17/sim/bd_6e42_m01arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_18/sim/bd_6e42_m01rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_19/sim/bd_6e42_m01awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_20/sim/bd_6e42_m01wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_21/sim/bd_6e42_m01bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_11/sim/bd_6e42_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_12/sim/bd_6e42_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_13/sim/bd_6e42_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_14/sim/bd_6e42_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_15/sim/bd_6e42_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_7/sim/bd_6e42_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_8/sim/bd_6e42_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_9/sim/bd_6e42_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/4e7b/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_2/sim/bd_6e42_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_3/sim/bd_6e42_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_4/sim/bd_6e42_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/sim/bd_6e42_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/sim/bd_6e42_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_0/sim/bd_6e42_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/sim/bd_6e42_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2/sim/design_1_axi_smc_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps7_0_50M_2/sim/design_1_rst_ps7_0_50M_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_2/sim/design_1_axi_gpio_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/0c68/src" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/design_1/ipshared/0c68/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/serval/ndnquang/cnn_circuit/vivado_pro/reM/project_1/project_1.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
