# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/design_1_axi_smc_2.xci
# IP: The module: 'design_1_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/bd_6e42.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_10/bd_6e42_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_16/bd_6e42_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_23/bd_6e42_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_30/bd_6e42_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_37/bd_6e42_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_44/bd_6e42_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_51/bd_6e42_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_57/bd_6e42_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_52/bd_6e42_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_53/bd_6e42_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_54/bd_6e42_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_55/bd_6e42_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_56/bd_6e42_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_50/bd_6e42_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_45/bd_6e42_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_46/bd_6e42_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_47/bd_6e42_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_48/bd_6e42_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_49/bd_6e42_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_43/bd_6e42_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_38/bd_6e42_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_39/bd_6e42_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_40/bd_6e42_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_41/bd_6e42_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_42/bd_6e42_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_36/bd_6e42_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_31/bd_6e42_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_32/bd_6e42_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_33/bd_6e42_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_34/bd_6e42_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_35/bd_6e42_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_29/bd_6e42_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_24/bd_6e42_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_25/bd_6e42_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_26/bd_6e42_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_27/bd_6e42_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_28/bd_6e42_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_22/bd_6e42_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_17/bd_6e42_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_18/bd_6e42_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_19/bd_6e42_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_20/bd_6e42_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_21/bd_6e42_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_11/bd_6e42_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_12/bd_6e42_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_13/bd_6e42_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_14/bd_6e42_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_15/bd_6e42_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_7/bd_6e42_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_8/bd_6e42_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_9/bd_6e42_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_2/bd_6e42_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_3/bd_6e42_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_4/bd_6e42_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/bd_6e42_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/bd_6e42_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_0/bd_6e42_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_10/bd_6e42_s00a2s_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_16/bd_6e42_m01s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_23/bd_6e42_m02s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_30/bd_6e42_m03s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_37/bd_6e42_m04s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_44/bd_6e42_m05s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_51/bd_6e42_m06s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_52/bd_6e42_m06arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_53/bd_6e42_m06rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_54/bd_6e42_m06awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_55/bd_6e42_m06wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_56/bd_6e42_m06bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_45/bd_6e42_m05arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_46/bd_6e42_m05rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_47/bd_6e42_m05awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_48/bd_6e42_m05wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_49/bd_6e42_m05bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_38/bd_6e42_m04arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_39/bd_6e42_m04rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_40/bd_6e42_m04awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_41/bd_6e42_m04wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_42/bd_6e42_m04bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_31/bd_6e42_m03arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_32/bd_6e42_m03rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_33/bd_6e42_m03awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_34/bd_6e42_m03wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_35/bd_6e42_m03bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_24/bd_6e42_m02arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_25/bd_6e42_m02rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_26/bd_6e42_m02awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_27/bd_6e42_m02wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_28/bd_6e42_m02bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_17/bd_6e42_m01arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_18/bd_6e42_m01rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_19/bd_6e42_m01awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_20/bd_6e42_m01wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_21/bd_6e42_m01bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_11/bd_6e42_sarn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_12/bd_6e42_srn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_13/bd_6e42_sawn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_14/bd_6e42_swn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_15/bd_6e42_sbn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_2/bd_6e42_arsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_3/bd_6e42_rsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_4/bd_6e42_awsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/bd_6e42_wsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/bd_6e42_bsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/design_1_axi_smc_2.xci
# IP: The module: 'design_1_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/bd_6e42.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_10/bd_6e42_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_16/bd_6e42_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_23/bd_6e42_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_30/bd_6e42_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_37/bd_6e42_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_44/bd_6e42_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_51/bd_6e42_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_57/bd_6e42_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_52/bd_6e42_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_53/bd_6e42_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_54/bd_6e42_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_55/bd_6e42_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_56/bd_6e42_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_50/bd_6e42_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_45/bd_6e42_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_46/bd_6e42_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_47/bd_6e42_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_48/bd_6e42_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_49/bd_6e42_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_43/bd_6e42_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_38/bd_6e42_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_39/bd_6e42_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_40/bd_6e42_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_41/bd_6e42_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_42/bd_6e42_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_36/bd_6e42_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_31/bd_6e42_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_32/bd_6e42_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_33/bd_6e42_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_34/bd_6e42_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_35/bd_6e42_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_29/bd_6e42_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_24/bd_6e42_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_25/bd_6e42_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_26/bd_6e42_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_27/bd_6e42_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_28/bd_6e42_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_22/bd_6e42_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_17/bd_6e42_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_18/bd_6e42_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_19/bd_6e42_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_20/bd_6e42_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_21/bd_6e42_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_11/bd_6e42_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_12/bd_6e42_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_13/bd_6e42_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_14/bd_6e42_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_15/bd_6e42_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_7/bd_6e42_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_8/bd_6e42_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_9/bd_6e42_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_2/bd_6e42_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_3/bd_6e42_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_4/bd_6e42_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/bd_6e42_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/bd_6e42_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_0/bd_6e42_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_10/bd_6e42_s00a2s_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_16/bd_6e42_m01s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_23/bd_6e42_m02s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_30/bd_6e42_m03s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_37/bd_6e42_m04s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_44/bd_6e42_m05s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_51/bd_6e42_m06s2a_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_52/bd_6e42_m06arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_53/bd_6e42_m06rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_54/bd_6e42_m06awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_55/bd_6e42_m06wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_56/bd_6e42_m06bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_45/bd_6e42_m05arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_46/bd_6e42_m05rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_47/bd_6e42_m05awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_48/bd_6e42_m05wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_49/bd_6e42_m05bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_38/bd_6e42_m04arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_39/bd_6e42_m04rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_40/bd_6e42_m04awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_41/bd_6e42_m04wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_42/bd_6e42_m04bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_31/bd_6e42_m03arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_32/bd_6e42_m03rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_33/bd_6e42_m03awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_34/bd_6e42_m03wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_35/bd_6e42_m03bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_24/bd_6e42_m02arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_25/bd_6e42_m02rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_26/bd_6e42_m02awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_27/bd_6e42_m02wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_28/bd_6e42_m02bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_17/bd_6e42_m01arn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_18/bd_6e42_m01rn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_19/bd_6e42_m01awn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_20/bd_6e42_m01wn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_21/bd_6e42_m01bn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_11/bd_6e42_sarn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_12/bd_6e42_srn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_13/bd_6e42_sawn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_14/bd_6e42_swn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_15/bd_6e42_sbn_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_2/bd_6e42_arsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_3/bd_6e42_rsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_4/bd_6e42_awsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_5/bd_6e42_wsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_6/bd_6e42_bsw_0_ooc.xdc

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/bd_0/ip/ip_1/bd_6e42_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/serval/daniel_shih/cnn_circuit/vivado_pro/reM/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
